DjangoMyProject1/urls.py
"""
Definition of urls for DjangoMyProject1.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^pool$', app.views.pool, name='pool'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost', app.views.videopost, name='videopost'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Авторизация',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from.models import Comment
from.models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))
class AnketaForm(forms.Form):
    name = forms.CharField(label='Имя',min_length=2,max_length=100)
    city = forms.CharField(label='Город',min_length=2,max_length=100)
    job = forms.CharField(label='Род занятий',min_length=2,max_length=100)
    gender = forms.ChoiceField(label='Пол',
                                choices=[('1','Мужской'),('2','Женский')],
                                widget=forms.RadioSelect,initial=1)
    trial = forms.ChoiceField(label='Посещали ли Вы наш автосервис?',
                              choices=(
                                  ('1','Да, я ваш постоянный клиент'),
                                  ('2','Собираюсь обратиться'),
                                  ('3','Нет'),
                                  ('4','Да, но мне не понравилось')),initial=1)
    notice = forms.BooleanField(label = 'Хотите получать интересные предложения по E-mail?',
                                required=False)
    email = forms.EmailField(label='Ваш E-mail',min_length=7)
    message = forms.CharField(label='Напишите мнение о нас',
                              widget=forms.Textarea(attrs={'rows':8,'cols':40}))

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment     #Используемая модель
        fields = ('text',)  #Требуется заполнить только поле текст
        labels = {'text':"Комментарий"} #Метка к полю формы text
        widgets = {
            'text':forms.Textarea(attrs={'rows': 10,'class': 'form-control'})
            }

class BlogForm (forms.ModelForm):
    class Meta:
        model=Blog      #Используемая модель
        fields = ('title','description','content','posted','author','image',)
        labels = {'title':"Заголовок",'description':"Краткое описание",'content':"Содержание",'posted':"Дата",'author':"Автор",'image':"Изображение"}

app/templates/app/about.html
{% extends "app/layout.html" %}
{% load staticfiles %}

{% block content %}


<section>
    <div class="o_nas">
        <h2>{{ title }}.</h2>
        <h3>{{ message }}</h3>
        <h3>Добро пожаловать на сайт Автосервиса "Колесо".</h3><br/>
        <p>Применение компьютерной диагностики и других современных технических средств – гарантия профессионального подхода, точного обнаружения неполадок. Наш автосервис оказывает услуги клиентам из Пскова, Санкт-Петербурга и даже Москвы. Вы доверяете автомобиль мастерам, которые знают свое дело и готовы произвести ремонт даже самой сложной поломки. Также мы предлагаем автовладельцам воспользоваться бесконтактной мойкой.</p><br/><br/>
        <h3>Почему же выбирают именно наш автосервис???</h3>
        <p>Мастера автосервиса оказывают профессиональные услуги по ремонту, диагностике и техническому обслуживанию автомобилей любых марок и производителей. Комплексный ремонт двигателя, кузовные работы, ремонт генератора и стартера, техобслуживание – вы обращаетесь к специалистам, которые учитывают функциональные особенности транспортных средств, характеристики, предлагают лучшие варианты решения проблем. К основным преимуществам нашего автосервиса относятся:</p><br />
        <ul>
            <li>строгое соблюдение установленных сроков проведения работ, которые заранее согласовываются с каждым клиентом;</li>
            <li>после осуществления ремонта и технического обслуживания автомобиля компания предоставляет гарантийное обслуживание. Это является гарантией высокого качества оказываемых услуг, мастерства и профессионализма каждого сотрудника автомастерской;</li>
            <li>специалисты работают с автомобилями всех марок и мировых производителей;</li>
            <li>доступные цены на весь перечень услуг.</li>
        </ul><br/><br/>
        <p>В нашем автосервисе закупается техника, необходимая для оказания всего перечня ремонтных услуг:</p><br />
        <ul>
            <li>диагностический стенд с компьютерным оборудованием, сканером;</li>
            <li>стенд для регулировки развал-схождения с датчиками;</li>
            <li>шиномонтажное оборудование;</li>
            <li>сварочное оборудование;</li>
            <li>мотор-тестер;</li>
            <li>оборудование для рихтовки;</li>
            <li>краскопульт;</li>
            <li>подъемники;</li>
            <li>домкраты и др.</li>            
        </ul><br/><br />
        <p>Нас можно найти по адресу г.Псков ул.Леона Поземского д.11 Предварительная запись или консультация по телефону +79922341767. Ждем у нас с вашей "ласточкой".</p>
    </div>   
</section>
{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
<div class="o_nas">
    <h2>{{ title }}</h2><br />

    {% for post in posts %}
        <hr />
        <div class="">
        <h2> {{post.title}} </h2>
        <h4> {{post.posted}} </h4>
        <p> {{post.description}} </p>
        <p><button class="button_read" onclick="document.location='{% url 'blogpost' parametr=post.id %}'">Читать статью</button></p>
        </div>

    {% endfor %}
</div>
{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}

{% block content %}
<div class="o_nas">
    <h2>{{ post_1.title }}</h2>
    {% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
        <img src="{{ post_1.image.url }}" alt="Картинка" width="300px" height="200px" />
    {% endif %}
    <p> {{post_1.content|linebreaksbr}} </p>    {# вывод текста по абзацам #}
    <p><a href="{% url 'blog' %}">Назад</a></p>

    {% if user.is_authenticated %}
     <h3>Оставить комментарий</h3>
     <form method="POST">{% csrf_token %}    {# защита от атак CSRF #}
        <div>
            {{form.as_p}}<br />
            <button type="submit" class="save btn btn-default">Отправить комментарий</button>
        </div>
     </form>
    {% else %}
        <h3>Чтобы оставить комментарий, пожалуйста, авторизуйтесь.</h3>
    {% endif %}

    {% for comment in comments %}
    <hr />
    <h7>{{comment.date}}</h7>
    <h5>{{comment.author}}</h5>
    <p>{{comment.text|linebreaksbr}}</p>
    {% endfor %}
</div>
{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}
<div class="o_nas">
    <h2>{{ title }}.</h2>
    <h3>{{ message }}</h3>

    <address>
        Автосервис "Колесо"<br />
        Ул.Леона Поземского, д.11<br />
        <abbr title="Телефон">Тел:</abbr>
        +79922341767
    </address>
    
   <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A55d19a6671af7111a793d3bb5c1d81ea8cd2dcbc98685f5e7023f523efed66ed&amp;source=constructor" width="500" height="400" frameborder="0"></iframe>

    <address>
        <strong>Техническая поддержка</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Отдел маркетинга</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</div>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% load staticfiles %}


{% block content %}
<div class="o_nas">
                    <section id="banner">
                         <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
                            <ol class="carousel-indicators">
                                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                                <li data-target="#myCarousel" data-slide-to="1"></li>
                                <li data-target="#myCarousel" data-slide-to="2"></li>
                            </ol>

                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="{% static 'app/content/volvo.png'%} " alt="Первый слайд" class="img-responsive" />
                                    <div class="carousel-caption" role="option">
                                            <button onclick="document.location='9'" class="button1"><span>Перейти к статье блога</span></button>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="{% static 'app/content/lexus.png'%}" alt="Второй слайд"  class="img-responsive" />
                                    <div class="carousel-caption" role="option">
                                            <button onclick="document.location='11'" class="button1"><span>Перейти к статье блога</span></button>
                                    </div>
                                </div>

                                <div class="item">
                                    <img src="{% static 'app/content/pejo.png'%}" alt="Третий слайд"  class="img-responsive" />
                                    <div class="carousel-caption" role="option">
                                            <button onclick="document.location='12'" class="button1"><span>Перейти к статье блога</span></button>
                                    </div>
                                </div>
                            </div>

                            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>

                            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>

                        </div>
                    </section>
          <h3>Вводное слово</h3>
          <p>
              Колесо – автосервис в городе Псков. Мы хотим на своем примере изменить отношение автомобилистов к автосервисам. Мы ценим честность и открытость в отношениях с нашими клиентами. Ремонт автомобилей у нас – это гарантия не только высокого качества оказываемых услуг, но и того, что все происходящее с Вашим автомобилем будет понятно и технически обосновано.
          </p>
          <p>
              Стараемся обеспечить высокий уровень сервиса автомобилей и максимально охватить все этапы цикла диагностики, ремонта и технического обслуживания авто. Обслуживая свою машину у нас, Вы можете не тревожиться ни о чём. Все стадии процесса будут профессионально организованы. Вам достаточно привезти неисправный авто, и получить его обратно уже отремонтированным. Нет необходимости тратить силы и время на поиск необходимых деталей и расходных материалов. Купить запчасти для автомобиля можно у нас. При этом у Вас всегда будет возможность посетить нашу ремонт зону, увидеть, что и как делается, и получить аргументированные ответы на любые поставленные вопросы. По всем авто ведется история обслуживания – в любой момент можно уточнить, какие работы и когда проводились, и какие запчасти использовались. 
          </p> 
          <p>
              Предлагаем запчасти для машин, расходные материалы и технические жидкости. Предпочитаем работать с официальными представителями, что гарантирует высокое качество продаваемой продукции и дает возможность выполнять гарантийные обязательства почти по всем группам товаров. Наш опыт позволяет выбирать оптимальные автозапчасти по соотношению цена/качество, что помогает экономить на ремонте без ухудшения его результатов. 
          </p>  
</div>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="{% static 'app/content/logo.png' %}" alt="logo" width="40"heght="40" /></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    <li><a href="{% url 'pool' %}">Обратная связь</a></li>
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                    {% if not user.is_authenticated %}
                    <li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавить статью</a></li>  
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Первое приложение на Django</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}
    {% load staticfiles %}
<div class="o_nas">    
    <h2>{{ title }}.</h2>
    <h3>{{ message }}</h3>

    <table>
        <tr>
            <td align="center"><a href ="http://radius47.ru/" target="_blank"> <img src="{% static 'app/content/radius.png' %}" alt="Logo 1" width="300px" height="200px"/></a></td>
            <td align="center"><a href ="https://spb.zzap.ru/" target="_blank"> <img src="{% static 'app/content/zzap.png' %}" alt="Logo 2" width="300px" height="200px"/></a></td>
            <td align="center"><a href ="https://www.astaworld.ru/" target="_blank"> <img src="{% static 'app/content/asta.png' %}" alt="Logo 3" width="300px" height="200px"/></a></td>
        </tr>
        <tr>
            <td><p>Автосервис «Radius»</p> <p>Предлагает большой выбор услуг по обслуживанию автомобиля, а также диагностические карты и помощь в автостраховании</p></td>
            <td><p>Интернет магазин поиска запчастей "Zzap.ru"</p><p>Вы всегда имеете возможность свободно выбрать на сайте того поставщика автозапчастей, который предложит наиболее выгодные цены и высококачественные детали.</p></td>
            <td><p>Компания "АСТА ассоциация"</p><p>Компания осуществляет поставки запчастей для легковых и грузовых автомобилей отечественного и зарубежного производства, а также спецтехники и тракторов.</p></td>
        </tr>
    </table>
</div>
{% endblock %}

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<div class="o_nas">
    <h2>{{ title }}</h2>
    <div class="row">
        <div class="col-md-8">
            <section id="loginForm">
                <form action="." method="post" class="form-horizontal">
                    {% csrf_token %}
                    <h4>Используйте созданный ранее аккаунт.</h4>
                    <hr />
                    <div class="form-group">
                        <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                        <div class="col-md-10">
                            {{ form.username }}
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="id_password" class="col-md-2 control-label">Пароль</label>
                        <div class="col-md-10">
                            {{ form.password }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="hidden" name="next" value="/" />
                            <input type="submit" value="Войти" class="btn btn-default" />
                        </div>
                    </div>
                    {% if form.errors %}
                    <p class="validation-summary-errors">Пожалуйста, введите логин и пароль правильно.</p>
                    {% endif %}
                </form>
            </section>
        </div>
        <div class="col-md-4">
            <section id="socialLoginForm"></section>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Здравствуйте, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Вход</a></li>
</ul>

{% endif %}

app/templates/app/newpost.html
{% extends "app/layout.html" %}

{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data"> {% csrf_token %} 
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-default">Сохранить статью</button>
    </div>
</form>

{% endblock %}

app/templates/app/pool.html
{% extends "app/layout.html" %}

{% block content %}

<div class="o_nas">
    {% if form != None %}
    <h2>{{ title }}</h2>
    <h3>{{ message }}</h3>
            <section id="PoolForm">
                <form method="POST" class="form-horizontal">
                    {% csrf_token %}
                    <label for = "{{ form.name.id_for_label }}"> {{ form.name.label }}: </label><br>
                        {{ form.name }}<br><br>
                    <label for = "{{ form.city.id_for_label }}"> {{ form.city.label }}: </label><br>
                        {{ form.city }}<br><br>
                    <label for = "{{ form.gender.id_for_label }}"> {{ form.gender.label }}: </label><br>
                        {{ form.gender }}<br><br>
                    <label for = "{{ form.job.id_for_label }}"> {{ form.job.label }}: </label><br>
                        {{ form.job }}<br><br>
                    <label for = "{{ form.trial.id_for_label }}"> {{ form.trial.label }}: </label><br>
                        {{ form.trial }}<br><br>
                    <label for = "{{ form.notice.id_for_label }}"> {{ form.notice.label }}: </label><br>
                        {{ form.notice }}<br><br>
                    <label for = "{{ form.email.id_for_label }}"> {{ form.email.label }}: </label><br>
                        {{ form.email }}<br><br>
                    <label for = "{{ form.message.id_for_label }}"> {{ form.message.label }}: </label><br>
                        {{ form.message }}<br><br>
                    <input type="submit" value="Отправить" class="submit_btn" />
                </form>
            </section>

    {% else %}
            <br><h2>Спасибо что заполнили анкету!</h2>
            <h3>Следующая информация о Вас сохранена в нашей базе:</h3>
            <ul>
                <li><span>Имя: </span> {{ data.name }} </li>
                <li><span>Город: </span> {{ data.city }} </li>
                <li><span>Пол: </span> {{ data.gender }} </li>
                <li><span>Род деятельности: </span> {{ data.job }} </li>
                <li><span>Посещали ли Вы наш автосервис: </span> {{ data.trial }} </li>
                <li><span>Рассылка E-mail: </span> {{ data.notice }} </li>
                <li><span>Ваш E-mail: </span> {{ data.email }} </li>
                <li><span>Мнение об автосервисе: </span> {{ data.message }} </li>
            </ul>
    {% endif %}
</div>
    <script>

        function button_mouse()
        {
            $('.submit_btn').css('color', 'indigo');
            $('.submit_btn').css('background-color', 'yellow');
        }

        function button_mouseleave()
        {
            $('.submit_btn').css('color', 'black');
            $('.submit_btn').css('background-color', 'white');
        }

        function field_name()
        {
        $('#id_name').css('background-color','cyan');
        }
        function field_name2()
        {
         $('#id_name').css('background-color','white');
        }
        function field_city()
        {
         $('#id_city').css('background-color','cyan');
        }
        function field_city2()
        {
         $('#id_city').css('background-color','white');
        }
        function field_job()
        {
         $('#id_job').css('background-color','cyan');
        }
        function field_job2()
        {
         $('#id_job').css('background-color','white');
        }
        function field_trial()
        {
         $('#id_trial').css('background-color', 'cyan');
        }
        function field_trial2()
        {
         $('#id_trial').css('background-color', 'white');
        }
        function field_notice()
        {
         $('#id_notice').css('background-color', 'cyan');
        }
        function field_notice2()
        {
         $('#id_notice').css('background-color', 'white');
        }
        function field_email()
        {
         $('#id_email').css('background-color', 'cyan');
        }
        function field_email2()
        {
         $('#id_email').css('background-color', 'white');
        }
        function field_message()
        {
         $('#id_message').css('background-color','cyan');
        }
        function field_message2()
        {
         $('#id_message').css('background-color','white');
        }
    
        $('.submit_btn').mouseover(button_mouse);
        $('.submit_btn').mouseout(button_mouseleave);

        $('#id_name').mouseover(field_name);
        $('#id_name').mouseout(field_name2);
        $('#id_city').mouseover(field_city);
        $('#id_city').mouseout(field_city2);
        $('#id_job').mouseover(field_job);
        $('#id_job').mouseout(field_job2);
        $('#id_trial').mouseover(field_trial);
        $('#id_trial').mouseout(field_trial2);
        $('#id_notice').mouseover(field_notice);
        $('#id_notice').mouseout(field_notice2);
        $('#id_email').mouseover(field_email);
        $('#id_email').mouseout(field_email2);
        $('#id_message').mouseover(field_message);
        $('#id_message').mouseout(field_message2);

    </script>

{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}

{% block content %}
<div class="o_nas">
    <h2>Регистрация пользователя</h2>

    <form method="POST" > {% csrf_token %}

        <div>
           
            {{ regform.as_p}}

            <button type="submit" class="save btn btn-default" > Зарегистрироваться </button>

        </div>

    </form>
</div>

{% endblock %}

app/templates/app/videopost.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<div class="o_nas">
    <h2>{{ title }}.</h2>
    <h3>{{ message }}</h3>

    <section>
        <div class="videopost">
            <h1>Видеоролик 1</h1>
            <VIDEO src="/media/rem1.mp4" controls="controls" width="400" height="300" poster="/media/rem1.jpg"></VIDEO>
        </div>

        <hr />

        <div class="videopost">
            <h1>Видеоролик 2</h1>
            <VIDEO src="/media/rem2.mp4" controls="controls" width="400" height="300" poster="/media/rem2.jpg"></VIDEO>
        </div>
    </section>
</div>
{% endblock %}